version: "3.7"
services:
  devel:
    image: node:12.19.0-stretch
    working_dir: /app
    command: sleep infinity
    network_mode: host
    volumes:
      - '../.:/app'
    ports:
      - 1337:1337

